Implemented predict prodigy functionality.
MantisAI/mantis pull request #1
Opened 2021-07-05 06:56 UTC by Eleni170

2021-07-05 07:51 UTC, nsorros commented on mantis/cli.py
> +from mantis.predict import predict_prodigy as predict_prodigy
is the `as` needed? isn't this enough `from mantis.predict import predict_prodigy`

2021-07-05 07:56 UTC, nsorros commented on mantis/predict.py
> +    evaluator = Evaluator(true=true, pred=pred, tags=tags_list, loader=None)
I would not do the following lines. I would save the predictions that Evaluator accepts and then the user would need to run
`nervaluate true_path pred_path`. So this function role is just to create the `pred_path` data

2021-07-05 07:57 UTC, nsorros requested changes
Just a small API change and this is ready to go

2021-07-06 06:38 UTC, Eleni170 commented
Ok I understood what you are talking about. You can see the changes.

2021-07-06 13:29 UTC, nsorros commented on tests/test_predict.py
> +    predict_prodigy(model_path=model_path, data_path=data_path)
I guess you can assert that data are created

2021-07-06 13:30 UTC, nsorros approved these changes

2021-08-04 11:23 UTC, merged